---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  labels:
    app: istiod
spec:
  selector:
    matchLabels:
      app: istiod
  endpoints:
  - port: http-monitoring
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - istio-system
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-ingressgateway
  labels:
    app: istio-ingressgateway
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  podMetricsEndpoints:
  - port: http-envoy-prom
    path: /stats/prometheus
    interval: 30s
  namespaceSelector:
    matchNames:
    - istio-system
