---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-xml
      - id: check-toml
      - id: pretty-format-json
        args: [--autofix]
      - id: check-json
      - id: check-executables-have-shebangs

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.2
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_fmt
      - id: terragrunt_fmt

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/google/go-jsonnet
    rev: v0.18.0
    hooks:
      - id: jsonnet-format
      - id: jsonnet-lint

  #- repo: https://github.com/sirwart/ripsecrets.git
  #  # Set your version, be sure to use the latest and update regularly or use 'main'
  #  rev: v0.1.3
  #  hooks:
  #    - id: ripsecrets
