apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: remote
  values:
    istiodRemote:
      injectionPath: /inject/cluster/serverless-cluster-a/net/serverless-cluster-a-network
    global:
      remotePilotAddress: "35.240.156.67"