apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress
spec:
  revision: ""
  profile: empty
  components:
    ingressGateways:
      - name: istio-ingressgateway
        label:
          istio: ingressgateway
          app: istio-ingressgateway
          topology.istio.io/network: serverless-cluster-b-network
        enabled: true
        k8s:
          env:
            # traffic through this gateway should be routed inside the network
            - name: ISTIO_META_REQUESTED_NETWORK_VIEW
              value: serverless-cluster-b-network
          service:
            loadBalancerIP: 34.126.91.172
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                targetPort: 15017
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
    global:
      network: serverless-cluster-b-network
